# Generated by Django 3.1 on 2020-08-15 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagava_users', '0002_auto_20200815_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 14, 27, 4, 260497)),
        ),
    ]
