# Generated by Django 3.1 on 2020-08-15 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tagava_users', '0005_auto_20200815_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 15, 20, 45, 645002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 15, 25, 45, 645038, tzinfo=utc)),
        ),
    ]
